<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>Local</ProjectType>
    <OutputType>Library</OutputType>
    <AssemblyName>OpenMetaverse.Rendering.Simple</AssemblyName>
    <PackageId>UtopiaSkye.OpenMetaverse.Rendering.Simple</PackageId>
    <Description>Simple faceted primitive mesh renderer for the OpenMetaverse library.</Description>
    <Authors>OpenSim NGC</Authors>
    <Company>Utopia Skye LLC</Company>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenMetaverse.Types\OpenMetaverse.Types.csproj" />
    <ProjectReference Include="..\OpenMetaverse\OpenMetaverse.csproj" />
  </ItemGroup>
</Project>
