name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh
    - name: Build
      run: msbuild /p:Configuration=Release OpenMetaverse.sln
      
