name: msbuild48

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: shortsha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"     
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh
    - name: Build
      run: msbuild /p:Configuration=Release OpenMetaverse.sln
    - name: release
      run: zip -r LastBuild.zip bin LICENSE.txt
    - uses: softprops/action-gh-release@v1
      with:
          tag_name:  r${{ steps.vars.outputs.sha_short }}
          name: LastBuild
          files: LastBuild.zip      
