name: msbuild48

on:
  push:
    branches: [ "master" ]
    paths:
       - '**.cs'
  workflow_dispatch:
 
jobs:
  build:
    if: github.repository == 'UbitUmarov/libopenmetaverse'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: readshortsha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"     
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild48.sh
    - name: Build
      id: build
      run: echo "::set-output name=errors::$(msbuild /p:Configuration=Release OpenMetaverse.sln)"
    - name: release
      if: success()
      run: zip -r LastBuild.zip bin LICENSE.txt
    - uses: softprops/action-gh-release@v1
      if: success()
      with:
          tag_name:  r${{ steps.vars.outputs.sha_short }}
          name: LastAutoBuild
          files: LastBuild.zip
    - name: report push to irc
      if: github.event_name == 'push'
      uses: rectalogic/notify-irc@v1
      with:
        channel: "#opensim-dev"
        server: "irc.libera.chat"
        nickname: osgithub
        message: |
          ${{ github.actor }} pushed to ${{ github.repository }}
          ${{ join(github.event.commits.*.message, '\n') }}
          compiled errors: ${{ steps.build.outputs.errors }}
    - name: report manual irc
      if: github.event_name == 'push'
      uses: rectalogic/notify-irc@v1
      with:
        channel: "#opensim-dev"
        server: "irc.libera.chat"
        nickname: osgithub
        message: |
          ${{ github.repository }} compiled errors: ${{ steps.build.outputs.errors }}
