name: irc

on:
  push:
    branches: [ "master" ]
    paths:
       - '**.cs'
  workflow_dispatch:
 
jobs:
  irc:
    if: github.repository == 'UbitUmarov/libopenmetaverse'
    runs-on: ubuntu-latest

    steps:     
    - name: irc push
      uses: rectalogic/notify-irc@v1
      if: github.event_name == 'push'
      with:
        channel: "#opensim-dev"
        server: "irc.libera.chat"
        nickname: osgithub
        message: |
          ${{ github.actor }} pushed to ${{ github.repository }}
          ${{ join(github.event.commits.*.message, '\n') }}

    - name: irc work
      uses: rectalogic/notify-irc@v1
      if: github.event_name == 'workflow_dispatch'
      with:
        channel: "#opensim-dev"
        server: "irc.libera.chat"
        nickname: osgithub
        message: |
          'testing' ${{ github.repository }}
